#include <P16F877A.INC>
__CONFIG _CP_OFF & _PWRTE_OFF & _WDT_OFF & _XT_OSC & _LVP_OFF
;CONFIGURA LVP_OFF MUITO IMPORTANTE, POIS, USO PORTB COMO I/O
CBLOCK 0x20
AUX_1
AUX_2
POS_MENU
MENU_CONDICAO
C_LUZ
ENDC
#DEFINE BANCO0 BCF STATUS,RP0
#DEFINE BANCO1 BSF STATUS,RP0
#DEFINE LCD PORTB
#DEFINE B_DIR PORTD,0
#DEFINEB_ENTER PORTD,1
#DEFINELCD_RS PORTD,2
#DEFINELCD_E PORTD,3
#DEFINE LUZES PORTC

ORG 0X00
GOTO MAIN

ORG 0X04
GOTO MAIN

MAIN
BANCO1

MOVLW b'00010011'
MOVWF TRISD
MOVLW b'00000000'
MOVWF TRISB
MOVLW b'00000000'
MOVWF TRISC

BANCO0
CALL INICIA_LCD
CALL OK

;ROTINA PRINCIPAL-------------------------------
MOVLW 0x00
MOVWF POS_MENU
MOVWF C_LUZ

PRINCIPAL;CHECAGEM DO BOTOES
BTFSC B_DIR
CALL MENU
BTFSC B_ENTER
CALL CONTATORA
GOTO PRINCIPAL
;SUBROTINA NAVEGACAO NO MENU
MENU

;TRATAMENTO EFEITO BOUNCING DO BOTÃO----
MOVLW .60
CALL DL1S
BTFSSB_DIR
RETURN
;--------------------------------------------------------------------

MOVLW 0x00
MOVWF MENU_CONDICAO

INCF POS_MENU,0
MOVWF POS_MENU;SALVA O WORK EM
POS_MENU
CALL TABELA_MENU;SEGUNDO NA PILHA
MOVWF MENU_CONDICAO
BTFSC MENU_CONDICAO,0;AS CONDICOES SAO CHAMADAS COM GOTO POIS ASSIM NAO CORRE RISCO DE OVERFLOW NO STACK
GOTO SALA
BTFSC MENU_CONDICAO,1
GOTO COZINHA
BTFSC MENU_CONDICAO,2
GOTO COPA
BTFSC MENU_CONDICAO,3
GOTO HALL
BTFSC MENU_CONDICAO,4
GOTO QUARTO_1
BTFSC MENU_CONDICAO,5
GOTO QUARTO_2
BTFSC MENU_CONDICAO,6
GOTO GARAGEM
BTFSC MENU_CONDICAO,7
CALL ZERA_MENU
FIM
RETURN
TABELA_MENU
ADDWF PCL,1
;PCL
retlw b'10000000'; REINICIA_MENU
retlw b'00000001'; SALA
retlw b'00000010'; COZINHA
retlw b'00000100'; COPA
retlw b'00001000'; HALL
retlw b'00010000'; QUARTO_1
retlw b'00100000'; QUARTO_2
retlw b'01000000'; GARAGEM
retlw b'10000000'; REINICIA_MENU
;SUBROTINA DE ACIONAMENTO
CONTATORA

;TRATAMENTO EFEITO BOUNCING DO BOTÃO----
MOVLW .60
CALL DL1S
BTFSSB_ENTER
RETURN
.--------------------------------------------------------------------

CALL LINHA_2
CALL ON_OFF
LOOP
MOVLW .80
CALL DL1S
BTFSC B_DIR;BOTAO DIRECIONAL ACIONADO
VAI PARA MENU
RETURN
BTFSC B_ENTER;BOTAO ENTER ACIONADO
VAI LIGAR A LUZ
CALL ALGUMA_ACAO
GOTO LOOP
RETURN

ALGUMA_ACAO

;TRATAMENTO EFEITO BOUNCING DO BOTÃO----
MOVLW .60
CALL DL1S
BTFSS B_ENTER
RETURN
;---------------------------------------------------------

BTFSC MENU_CONDICAO,0
GOTO ACIONA_SALA
BTFSC MENU_CONDICAO,1
GOTO ACIONA_COZ
BTFSC MENU_CONDICAO,2
GOTO ACIONA_COPA
BTFSC MENU_CONDICAO,3
GOTO ACIONA_HALL
BTFSC MENU_CONDICAO,4
GOTO ACIONA_DORM1
BTFSC MENU_CONDICAO,5
GOTO ACIONA_DORM2
BTFSC MENU_CONDICAO,6
GOTO ACIONA_GAR
RETURN

;TESTE DE BIT COMODOS
ACIONA_SALA
BTFSC PORTC,0
GOTO L_D
BSF PORTC,0
RETURN

L_D
BCF PORTC,0
RETURN

ACIONA_COZ
BTFSC PORTC,1
GOTO L_CZ
BSF PORTC,1
RETURN

L_CZ
BCF PORTC,1
RETURN

ACIONA_COPA
BTFSC PORTC,2
GOTO L_CP
BSF PORTC,2
RETURN

L_CP
BCF PORTC,2
RETURN

ACIONA_HALL
BTFSC PORTC,3
GOTO L_HL
BSF PORTC,3
RETURN

L_HL
BCF PORTC,3
RETURN

ACIONA_DORM1
BTFSC PORTC,4
GOTO L_DM1
BSF PORTC,4
RETURN

L_DM1
BCF PORTC,4
RETURN

ACIONA_DORM2
BTFSC PORTC,5
GOTO L_DM2
BSF PORTC,5
RETURN

L_DM2
BCF PORTC,5
RETURN

ACIONA_GAR
BTFSC PORTC,6
GOTO L_GM
BSF PORTC,6
RETURN

L_GM
BCF PORTC,6
RETURN

ZERA_MENU;SETUP INICIAL
MOVLW 0x00
MOVWF POS_MENU
RETURN

;INICIALIZAÇÃO DO LCD
INICIA_LCD
BCF LCD_RS
BCF LCD_E
MOVLW .30
CALL DL1S

MOVLW b'00110000'; COMANDO INICIAL 1X
MOVWF LCD
CALL PULSO
MOVLW .10
CALL DL1S

MOVLW b'00110000'; COMANDO INICIAL 2X
MOVWF LCD
CALL PULSO
MOVLW .3
CALL DL1S

MOVLW b'00110000';COMANDO INICIAL 3X
MOVWF LCD
CALL PULSO
MOVLW .3
CALL DL1S
MOVLW b'00111100'
MOVWF LCD
CALL PULSO
MOVLW .5
CALL DL1S

MOVLW b'00001000';DISPLAY OFF
MOVWF LCD
CALL PULSO
MOVLW .5
CALL DL1S
MOVLW b'00001100';DISPLAY ON TA ERRADO NO DATASHEET FICAR ATENTO
MOVWF LCD
CALL PULSO
MOVLW .5
CALL DL1S
MOVLW b'00000110'
MOVWF LCD
CALL PULSO
MOVLW .10
CALL DL1S
RETURN

;SUBROTINAS DE NAVECAO NO MENU---------------
ON_OFF
BSF LCD_RS; HABILITAR A ESCRITA NO LDC
MOVLW 'O'
CALL ESCREVE
MOVLW 'N'
CALL ESCREVE
MOVLW '/'
CALL ESCREVE
MOVLW 'O'
CALL ESCREVE
MOVLW 'F'
CALL ESCREVE
MOVLW 'F'
CALL ESCREVE
BCF LCD_RS
RETURN
SALA
CALL LIMPA
BSF LCD_RS; HABILITAR A ESCRITA NO LDC
MOVLW 'S'
CALL ESCREVE
MOVLW 'A'
CALL ESCREVE
MOVLW 'L'
CALL ESCREVE
MOVLW 'A'
CALL ESCREVE
BCF LCD_RS
RETURN
HALL
CALL LIMPA
BSF LCD_RS; HABILITAR A ESCRITA NO LDC
MOVLW 'H'
CALL ESCREVE
MOVLW 'A'
CALL ESCREVE
MOVLW 'L'
CALL ESCREVE
MOVLW 'L'
CALL ESCREVE
BCF LCD_RS
RETURN
COPA
CALL LIMPA
BSF LCD_RS; HABILITAR A ESCRITA NO LDC
MOVLW 'C'
CALL ESCREVE
MOVLW 'O'
CALL ESCREVE
MOVLW 'P'
CALL ESCREVE
MOVLW 'A'
CALL ESCREVE
BCF LCD_RS
RETURN
COZINHA
CALL LIMPA
BSF LCD_RS;HABILITA A ESCRITA NO LDC
MOVLW 'C'
CALL ESCREVE
MOVLW 'O'
CALL ESCREVE
MOVLW 'Z'
CALL ESCREVE
MOVLW 'I'
CALL ESCREVE
MOVLW 'N'
CALL ESCREVE
MOVLW 'H'
CALL ESCREVE
MOVLW 'A'
CALL ESCREVE
BCF LCD_RS
RETURN
GARAGEM
CALL LIMPA
BSF LCD_RS; HABILITAR A ESCRITA NO LDC
MOVLW 'G'
CALL ESCREVE
MOVLW 'A'
CALL ESCREVE
MOVLW 'R'
CALL ESCREVE
MOVLW 'A'
CALL ESCREVE
MOVLW 'G'
CALL ESCREVE
MOVLW 'E'
CALL ESCREVE
MOVLW 'M'
CALL ESCREVE
BCF LCD_RS
RETURN
QUARTO_1
CALL LIMPA
BSF LCD_RS; HABILITAR A ESCRITA NO LDC
MOVLW 'Q'
CALL ESCREVE
MOVLW 'U'
CALL ESCREVE
MOVLW 'A'
CALL ESCREVE
MOVLW 'R'
CALL ESCREVE
MOVLW 'T'
CALL ESCREVE
MOVLW 'O'
CALL ESCREVE
MOVLW '1'
CALL ESCREVE
BCF LCD_RS
RETURN
QUARTO_2
CALL LIMPA
BSF LCD_RS; HABILITAR A ESCRITA NO LDC
MOVLW 'Q'
CALL ESCREVE
MOVLW 'U'
CALL ESCREVE
MOVLW 'A'
CALL ESCREVE
MOVLW 'R'
CALL ESCREVE
MOVLW 'T'
CALL ESCREVE
MOVLW 'O'
CALL ESCREVE
MOVLW '2'
CALL ESCREVE
BCF LCD_RS
RETURN
OK
BSF LCD_RS;HABILITA A ESCRITA NO LDC
MOVLW 'B'
CALL ESCREVE
MOVLW 'E'
CALL ESCREVE
MOVLW 'M'
CALL ESCREVE
MOVLW '-'
CALL ESCREVE
MOVLW 'V'
CALL ESCREVE
MOVLW 'I'
CALL ESCREVE
MOVLW 'N'
CALL ESCREVE
MOVLW 'D'
CALL ESCREVE
MOVLW 'O'
CALL ESCREVE
MOVLW '!'
CALL ESCREVE
BCF LCD_RS
RETURN
;COMANDOS PARA DISPLAY
ESCREVE
MOVWF LCD
CALL PULSO
RETURN
LIMPA
BCF LCD_RS
MOVLW b'00000001'
MOVWF PORTB
CALL PULSO
MOVLW .2
CALL DL1S
RETURN
PULSO
BSF LCD_E
MOVLW .10
CALL DL1S
BCF LCD_E
RETURN
LINHA_2
BCF LCD_RS
MOVLW b'11000000'
MOVWF PORTB
CALL PULSO
MOVLW .2
CALL DL1S
RETURN
;DELAYS
DL1S;DELAY VARIAVEL 1 ATÉ 250 MS
MOVWF AUX_1
DL1MS;DELAY 1 MS
MOVLW .250
MOVWF AUX_2
LACO
NOP
DECFSZ AUX_2,1
GOTO LACO
;FIM DELAY 1 MS
DECFSZ AUX_1,1
GOTO DL1MS
;FIM DELAY 250 MS
RETURN
END
